version: 0.0
os: linux
files:
  - source: /
    destination: /srv02
    overwrite: yes
hooks:
  BeforeInstall:
    - location: before_install.sh
      timeout: 45
      runas: root
  AfterInstall:
    - location: after_install.sh
      timeout: 45
      runas: root
  ApplicationStart:
    - location: start.sh
      timeout: 60
      runas: root
  ApplicationStop:
    - location: stop.sh
      timeout: 45
      runas: root
