version: 0.2
phases:
  install:
    runtime-versions:
      dotnet: 8.0.303
  pre-build:
    commands:
      - sudo dotnet restore
  build:
    commands:
      - sudo dotnet build -c Release
      - sudo dotnet publish -c Release --self-contained=false --runtime linux-x64 -o ./bin/Release/net8.0/linux-x64/publish/
artifacts:
  files:
    - publish/**/*
    - appspec.yml
    - scripts/*
  discard-paths: yes