version: 0.2
phases:
  install:
    runtime-versions:
      dotnet: 8.0.303
  build:
    commands:
      - dotnet restore
      - dotnet build -c Release
      - dotnet publish -c Release --self-contained=false --runtime linux-x64 -o ./publish/
artifacts:
  files:
    - publish/**/*
    - appspec.yml
    - scripts/*
  discard-paths: yes