version: 0.2
phases:
  install:
    runtime-versions:
      dotnet: 8.0
  build:
    commands:
      - dotnet publish -c Release --self-contained=false --runtime linux-x64 -o bin/Release/net8.0/linux-x64/
artifacts:
  files:
    - bin/Release/netcoreapp6/linux-x64/**/*
    - appspec.yml
    - scripts/*
  discard-pathes: yes